# Generated by Django 5.0.4 on 2024-04-25 07:57

import django.db.models.deletion
import order_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('usertype_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('email', models.CharField(default='null', max_length=264)),
                ('telephone', models.CharField(default='null', max_length=264)),
                ('address', models.TextField(default='null', max_length=264)),
                ('address_2', models.TextField(default='null', max_length=264)),
                ('clienttype_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_app.clienttype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=order_app.models.utc_tomorrow)),
                ('completed', models.CharField(choices=[('ENT', 'Entregado'), ('PROC', 'En proceso'), ('NOT', 'No se entregó')], default='PROC', max_length=4)),
                ('nota', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_app.client')),
                ('product', models.ForeignKey(default='Nacatamal de cerdo', on_delete=django.db.models.deletion.PROTECT, to='order_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
